dataset_path: "G:\\dataset\\dogs-vs-cats\\train"
batch_size: 128
epochs: 50
use_norm: true
use_drop: False
img_size: 224
network_type: 1
num_classes: 2
load_model: False
model_path: "weights/"
model_name: "resnext-w-mae-wo-drop"
train_mae: true
train_mode: true
use_pretrained_resnet: False
